# Generated by Django 3.0.5 on 2020-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prouser',
            name='points',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='prouser',
            name='rank',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
