# Generated by Django 3.0.5 on 2020-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200625_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='prouser',
            name='best_result',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prouser',
            name='test_runs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
