# Generated by Django 3.0.5 on 2020-07-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200708_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prouser',
            name='best_result',
        ),
        migrations.RemoveField(
            model_name='prouser',
            name='test_runs',
        ),
    ]
