# Generated by Django 3.0.5 on 2020-06-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0002_testresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ansver',
            new_name='Answer',
        ),
    ]
