# Generated by Django 3.0.5 on 2020-06-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0004_testresultdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultdetails',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
