# Generated by Django 3.0.5 on 2020-06-26 18:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0005_testresultdetails_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='testresultdetails',
            name='test_results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results_details', to='testsuite.TestResult'),
        ),
    ]
