# Generated by Django 3.0.5 on 2020-07-05 11:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testsuite', '0009_testrun_testrundetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrundetail',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='testrundetail',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testrundetail',
            name='test_suite_run',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='avg_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresultdetails',
            name='answered_questions',
        ),
        migrations.RemoveField(
            model_name='testresultdetails',
            name='given_answers',
        ),
        migrations.RemoveField(
            model_name='testresultdetails',
            name='test_results',
        ),
        migrations.AddField(
            model_name='testresult',
            name='datetime_run',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='testresult',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Started')], default=1),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_suite_runs', to='testsuite.Test'),
        ),
        migrations.AddField(
            model_name='testresultdetails',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testsuite.Answer'),
        ),
        migrations.AddField(
            model_name='testresultdetails',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsuite.Question'),
        ),
        migrations.AddField(
            model_name='testresultdetails',
            name='test_suite_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testsuite.TestResult'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suite_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
        migrations.DeleteModel(
            name='TestRunDetail',
        ),
    ]
