# Generated by Django 3.0.5 on 2020-07-05 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testsuite', '0010_auto_20200705_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='test_suite',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='testsuite.Test'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
