# Generated by Django 3.0.5 on 2020-07-05 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0013_auto_20200705_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
