# Generated by Django 3.0.5 on 2020-07-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0014_auto_20200705_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='current_question',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
