# Generated by Django 3.0.5 on 2020-07-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0016_auto_20200708_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestResults',
        ),
    ]
