# Generated by Django 3.0.5 on 2020-07-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0017_delete_bestresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='best_result',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
