# Generated by Django 3.0.5 on 2020-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0018_auto_20200708_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='number_of_completed_runs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='current_progress',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
