# Generated by Django 3.0.5 on 2020-07-08 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testsuite', '0019_auto_20200708_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='best_result',
        ),
        migrations.CreateModel(
            name='BestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_result', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_results', to='testsuite.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
