# Generated by Django 3.0.5 on 2020-07-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0020_auto_20200708_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestResults',
        ),
    ]
